discord:
  prefix: "?"
  logChannelID: "1402262636782944366"  # bothagen (logging)
  defaultChannelID: "1402262679745462453"  # kvardagsprat (hovudkanal)

approval:
  queueChannelID: "1402262743779774568"  # spørsmål (approval queue)
  opplysarRoleID: "1402262871966224444"  # utiviklar (admin rolle)

bannedwords:
  approvalChannelID: "1402312367542374532"  # retting (banned word approval)
  rettskrivarRoleID: "1381943546503761941"  # rettskrivar role

grammar:
  channelID: "1402287744985727167"  # grammatikk (for threads)

starboard:
  channelID: "1402262710279864370"  # stjernebrettet
  threshold: 1
  emoji: "🌟"  # Beta uses 🌟 instead of ⭐ to avoid collision

database:
  host: "malfolketno01.mysql.domeneshop.no"
  port: 3306
  dbname: "malfolketno01"
  # Beta will use daily_questions_testing table instead of daily_questions

scheduler:
  enabled: true
  timezone: "Europe/Oslo"
  morning_time: "08:00"     # 08:00 European time
  evening_time: "20:00"     # 20:00 European time
  inactivity_hours: 6       # Post after 6 hours of inactivity
  cron_string: "0 8 * * *"  # Fallback: 08:00 daily

reactions:
  question: "🔶"  # Beta uses 🔶 instead of ❓ to avoid collision

# Welcome messages for new members
welcome:
  enabled: true
  channelID: "1402262679745462453"  # kvardagsprat (same as default channel)
  message: "Velkommen til serveren, {user}! 🎉 Les gjerne {rules} og spør viss du lurer på noko."

# Rules information
rules:
  title: "📋 Serverreglar"
  content: |
    **Hovudreglar:**
    • Ver respektfull mot andre medlemmar
    • Følg Discords retningslinjer
    • Hald deg til emna i kanalane
    • Spør gjerne om grammatikk og språk!
    
    **Grammatikkkanalen:**
    • Bruk 🔨-reaksjon for å rapportere feil ord
    • Bruk `?ord <ord>` for ordbok-oppslag
    • Bruk `?kontekst <ord> <setning>` for kontekstanalyse

# Beta-specific settings
environment: "beta"
table_suffix: "_testing"  # Will create daily_questions_testing

showAISlopWarning: true
aiSlopWarningText: |
  🧪 **BETA** - Denne botten bruker AI-generert kode og er i testing-modus. 
  Inntil alt er manuelt sjekket, kan det vere rare eller feilende ting i svaret!
